# Generated by Django 3.1.6 on 2021-02-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='meals',
            field=models.ManyToManyField(null=True, to='meals.Meal'),
        ),
    ]
