# Generated by Django 3.1.6 on 2021-02-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Meal',
        ),
    ]
