# Generated by Django 3.1.6 on 2021-02-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='meals',
        ),
        migrations.AddField(
            model_name='category',
            name='meals',
            field=models.ManyToManyField(to='meals.Meal'),
        ),
    ]
